<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Mono.Cecil" Version="0.11.6" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Ether.Api\Ether.Api.csproj" />
    <ProjectReference Include="..\..\src\Ether.Application\Ether.Application.csproj" />
    <ProjectReference Include="..\..\src\Ether.Contracts\Ether.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Ether.Domain\Ether.Domain.csproj" />
    <ProjectReference Include="..\..\src\Ether.GameServer\Ether.GameServer.csproj" />
    <ProjectReference Include="..\..\src\Ether.Infrastructure\Ether.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Ether.Worker\Ether.Worker.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
